/**
 * GitHub Plugin GraphQL Operations — TypedDocumentNode operations for UI components.
 *
 * All queries and mutations used by the GitHub plugin's UI are defined here.
 * Types are auto-generated by graphql-codegen from the schema.graphql.
 *
 * Run `pnpm codegen` after schema changes to regenerate types.
 *
 * @module plugin-github/client/operations
 */

import { graphql } from './generated/gql';

// ─────────────────────────────────────────────────────────────────────────────
// Nav Section Queries
// ─────────────────────────────────────────────────────────────────────────────

export const GET_MY_PRS = graphql(`
  query GetMyPRs($filter: String, $state: String, $limit: Int) {
    githubMyPRs(filter: $filter, state: $state, limit: $limit) {
      id
      number
      title
      state
      draft
      owner
      repo
      headBranch
      checksStatus
      reviewState
      url
      updatedAt
    }
  }
`);

export const GET_MY_ISSUES = graphql(`
  query GetMyIssues($query: String!, $limit: Int) {
    searchGithubIssues(query: $query, limit: $limit) {
      id
      number
      title
      state
      owner
      repo
      labels {
        name
        color
      }
      url
      updatedAt
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// PR Drawer Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_GITHUB_PR = graphql(`
  query GetGitHubPR($owner: String!, $repo: String!, $pullNumber: Int!) {
    githubPR(owner: $owner, repo: $repo, pullNumber: $pullNumber) {
      id
      number
      title
      state
      draft
      author
      authorAvatar
      owner
      repo
      headBranch
      baseBranch
      body
      additions
      deletions
      changedFiles
      mergeable
      reviewState
      checksStatus
      labels { name color }
      reviewers
      url
      createdAt
      updatedAt
    }
  }
`);

export const MERGE_GITHUB_PR = graphql(`
  mutation MergeGitHubPR($input: MergePRInput!) {
    githubMergePR(input: $input) {
      id number title state draft owner repo mergeableState
    }
  }
`);

export const UPDATE_GITHUB_PR = graphql(`
  mutation UpdateGitHubPR($input: UpdateGitHubPRInput!) {
    githubUpdatePR(input: $input) {
      id number title state body owner repo
      labels { name color }
      reviewers
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Issue Drawer Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_GITHUB_ISSUE = graphql(`
  query GetGitHubIssue($owner: String!, $repo: String!, $issueNumber: Int!) {
    githubIssue(owner: $owner, repo: $repo, issueNumber: $issueNumber) {
      id
      number
      title
      state
      author
      authorAvatar
      owner
      repo
      body
      labels { name color }
      assignees
      commentCount
      url
      createdAt
      updatedAt
      closedAt
    }
  }
`);

export const UPDATE_GITHUB_ISSUE = graphql(`
  mutation UpdateGitHubIssue($input: UpdateGitHubIssueInput!) {
    githubUpdateIssue(input: $input) {
      id number title state body owner repo
      labels { name color }
      assignees
      commentCount
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Repository Metadata Queries (for Combobox dropdowns)
// ─────────────────────────────────────────────────────────────────────────────

export const GET_REPO_LABELS = graphql(`
  query GetRepoLabels($owner: String!, $repo: String!) {
    githubRepoLabels(owner: $owner, repo: $repo) {
      name
      color
    }
  }
`);

export const GET_REPO_COLLABORATORS = graphql(`
  query GetRepoCollaborators($owner: String!, $repo: String!) {
    githubRepoCollaborators(owner: $owner, repo: $repo) {
      login
      avatarUrl
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Comment Mutations
// ─────────────────────────────────────────────────────────────────────────────

export const ADD_GITHUB_ISSUE_COMMENT = graphql(`
  mutation AddGitHubIssueComment($input: AddIssueCommentInput!) {
    githubAddIssueComment(input: $input) {
      id number title state owner repo commentCount
    }
  }
`);

export const ADD_GITHUB_PR_COMMENT = graphql(`
  mutation AddGitHubPRComment($input: AddPRCommentInput!) {
    githubAddPRComment(input: $input) {
      id number title state owner repo
    }
  }
`);
